### ISSUE TITLE
Python package needs updating?

### ISSUE THREAD

**Issue by rajramasawmy** [ismrmrd/ismrmrdviewer#11]
Searching for [ismrmrd](https://pypi.org/search/?q=ismrmrd&o=) on pypi I could only see the version from last year:

https://pypi.org/project/ismrmrd-viewer/#description
Running
```bash
pip3 install --user ismrmrd-viewer
```
(there was no "ismrmrdviewer") installed, but I couldn't get the module to work. 

Either python ismrmrd-viewer/ python -m ismrmrd-viewer

**Comment by dchansen** [comment]
A new and shiny ismrmrdviewer package is on pypi.
