### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by mrikasper** [ismrmrd/ismrmrdviewer#14]
Hi there,

thank you for creating such a nice package. I am a novice to python and struggle with getting it installed on Windows with an Anaconda Installation of Python.

I opened an Anaconda command prompt, but the step-by-step Windows installation instructions fail with

```
venv\bin\activate.bat
The system cannot find the path specified.
```

Do you have any recommendations? Would be great to make such a viewer accessible without needing a python installation.

All the best,
Lars

**Comment by kherz** [comment]
Hi Lars,
don't know if this is still active, but I just had to install the viewer on windows myself and stumbled upon this issue.

On windows, there is no bin folder, the activate scripts go to <venv>/Scripts (see here: https://docs.python.org/3/library/venv.html). However, there is also some restriction on running these scripts, which you probably don't want to change (see here for details: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1) 

What worked for me inside the conda shell was:

python3 -m venv venv
venv\Scripts\activate   (you might get some error here, but the virtual environment gets activated)
pip3 install -r requirements.txt 

Best,
Kai

**Comment by dchansen** [comment]
You should be able to install the viewer simply with
`pip install ismrmrdviewer`
from a terminal with python on the path (such as the Anaconda prompt).
Using virtual environments is completely optional.

**Comment by kherz** [comment]
Yes, I know. But with that I got some h5py wheel error on windows and the venv option was the fastest fix for me
