### ISSUE TITLE
LFS storage

### ISSUE THREAD

**Issue by dchansen** [ismrmrd/ismrmrdviewer#23]
Currently, the ismrmrdviewer repository is neutered by the fact that the ismrmrd organization is out of LFS storage.
This means noone can pull or push to ismrmrdviewer or indeed any forks, due to the novel way GitHub registers LFS storage.

Our options are: 
- Remove LFS objects from ismrmrdviewer (this means all tests data).
or 
- Pay for LFS.

@hansenms Could you guys be persuaded to sponsor the LFS data?

**Comment by hansenms** [comment]
@dchansen we don't really have a practical way of sponsoring that.

The data is not really used as test data as such (it is not needed at build time or in a pipeline).....more example data, so I think there are probably other options. Like putting the test in some other public data repo. That would be my suggestion.

**Comment by dchansen** [comment]
Turns out uninstalling git lfs from the repo solves the issue.
