### ISSUE TITLE
Incomplete installation?

### ISSUE THREAD

**Issue by roopchansinghv** [ismrmrd/ismrmrdviewer#8]
I've been trying to install the ismrmrd-viewer based on the repository available here.

I've tried running:

   python setup.py install

from both an Anaconda environment on macOS Mojave, and an openSUSE container.  In both cases, the installation is made to a virtual environment called 'viewertest'.  And in both cases, I see additional files:

   (viewertest root)/bin/ismrmrd-viewer
   (viewertest root)/lib/python3.6/site-packages/ismrmrd_viewer-0.0.2-py3.6.egg

the latter of which seems to be a flat file, and doesn't seem to include any contents of the 'src' directory, that's needed to support reading and viewing the raw files.  When I try to run the viewer:

   python (viewertest root)/bin/ismrmrd-viewer ScanArchive_20190529_090502374_converted.h5

I get the following error:

Traceback (most recent call last):
  File " (viewertest root)/bin/ismrmrd-viewer", line 11, in <module>
    load_entry_point('ismrmrd-viewer==0.0.2', 'gui_scripts', 'ismrmrd-viewer')()
  File " (viewertest root)/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File " (viewertest root)/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File " (viewertest root)/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File " (viewertest root)/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'viewer'

I feel like I am missing something really obvious.  I am also uploading the installation log for this package.

Maybe the issue is a missing __init.py__ in 'src'?

Many thanks!

[install_log.txt](https://github.com/ismrmrd/ismrmrd-viewer/files/4476091/install_log.txt)

**Comment by dchansen** [comment]
There were quite a few issues with how we installed the viewer. These should be fixed now. 
Could you check if the latest update works?

**Comment by roopchansinghv** [comment]
Yes - changes worked fine.  Installed, ran, and provided viewing window on macOS running Anaconda.

Thank you @dchansen!
